const express=require('express');const fs=require('fs');const path=require('path');const http=require('http');const {Server}=require('socket.io');
const app=express();const server=http.createServer(app);const io=new Server(server,{pingInterval:10000,pingTimeout:20000,maxHttpBufferSize:1e5});
app.disable('x-powered-by');app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');next()});
const DATA=path.join(__dirname,'data');const FILE=path.join(DATA,'players-v9.json');fs.mkdirSync(DATA,{recursive:true});let saved={};try{saved=JSON.parse(fs.readFileSync(FILE,'utf8'))||{}}catch{}
const persist=()=>{try{fs.writeFileSync(FILE,JSON.stringify(saved,null,2))}catch(e){console.error('save',e.message)}};
const W=9600,H=5400,TILE=48;const players=new Map(),battles=new Map(),invites=new Map();let owner=null,started=false;
const clean=s=>String(s||'Trainer').replace(/[^a-zA-Z0-9 _-]/g,'').trim().slice(0,18)||'Trainer';const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const mons={pikachu:{icon:'⚡',type:'Electric',hp:110,atk:22},raichu:{icon:'⚡',type:'Electric',hp:125,atk:27},squirtle:{icon:'💧',type:'Water',hp:125,atk:20},charmander:{icon:'🔥',type:'Fire',hp:105,atk:25},bulbasaur:{icon:'🌿',type:'Grass',hp:120,atk:21},pidgey:{icon:'🪽',type:'Flying',hp:100,atk:23},rayquaza:{icon:'🐉',type:'Dragon',hp:180,atk:38}};
const wild=[['Flameling','🔥','Fire',80,17],['Aquafin','💧','Water',88,15],['Leafling','🌿','Grass',84,16],['Skybit','🪽','Flying',72,19],['Voltimp','⚡','Electric',76,20],['Moonkit','🌙','Dark',90,16],['Pebblit','🪨','Rock',105,13],['Frostel','❄️','Ice',86,18],['Buglet','🐛','Bug',70,15],['Drakid','🐲','Dragon',95,21]];
const questions=[
['She _____ to school yesterday.',['go','went','goes','going'],1,'Past simple: “yesterday” calls for went.'],['Translate: El pájaro vuela alto.',['The bird flies high.','The bird runs fast.','The cat flies high.','The bird is small.'],0,'Bird = pájaro and flies = vuela.'],['English for “agua”.',['Fire','Water','Earth','Wind'],1,'Water means agua.'],['Past tense of eat?',['eated','eats','ate','eating'],2,'The irregular past of eat is ate.'],['Happy means…',['Triste','Feliz','Rápido','Grande'],1,'Happy means feliz.'],['They _____ playing football.',['is','am','are','be'],2,'They takes the plural verb are.'],['I ___ a student.',['am','is','are','be'],0,'I takes am.'],['Fast means…',['Lento','Rápido','Pequeño','Frío'],1,'Fast means rápido.'],['Choose the plural.',['childs','children','childes','child'],1,'Children is the irregular plural of child.'],['Opposite of cold.',['hot','slow','dark','short'],0,'Hot is the opposite of cold.'],['There _____ two books.',['is','are','am','be'],1,'Two books is plural, so use are.'],['My sister _____ a bike every day.',['ride','rides','riding','rode'],1,'Third-person singular in the present uses rides.'],['Translate: “I like music.”',['Me gusta la música.','Odio la música.','Toco fútbol.','Escucho agua.'],0,'I like = me gusta.'],['Which is a place?',['school','happy','quickly','blue'],0,'School is a place.'],['Choose the correct article: ___ apple.',['a','an','thee','some'],1,'Apple begins with a vowel sound: an apple.']];
const towns=[{id:'lumen',name:'Pueblo Lumen',x:850,y:700,region:'Pradera Lumen'},{id:'aqua',name:'Villa Aqua',x:3900,y:850,region:'Lago Azul'},{id:'nova',name:'Ciudad Nova',x:6900,y:1100,region:'Región Nova'},{id:'verde',name:'Aldea Verde',x:2150,y:3900,region:'Bosque Esmeralda'},{id:'cumbre',name:'Pueblo Cumbre',x:7700,y:3900,region:'Montañas Rojas'},{id:'sky',name:'Puerto Sky',x:5000,y:4550,region:'Costa Sky'}];
const regions=[{name:'Pradera Lumen',x:0,y:0,w:3000,h:1800,c:'#63b765'},{name:'Bosque Esmeralda',x:0,y:1800,w:3200,h:3600,c:'#3f9658'},{name:'Lago Azul',x:3000,y:0,w:3000,h:2500,c:'#5eae69'},{name:'Región Nova',x:6000,y:0,w:3600,h:2200,c:'#72b96a'},{name:'Montañas Rojas',x:6000,y:2200,w:3600,h:3200,c:'#7c7774'},{name:'Costa Sky',x:3200,y:2500,w:2800,h:2900,c:'#59a866'}];
const routes=[[850,700,3900,850],[3900,850,6900,1100],[6900,1100,7700,3900],[7700,3900,5000,4550],[5000,4550,2150,3900],[2150,3900,850,700],[3900,850,2150,3900],[5000,4550,6900,1100]];
const grass=[[1150,300,2750,650],[1500,900,2850,1550],[350,2250,1700,3450],[1800,2300,3050,3550],[3000,300,3700,650],[4800,300,5900,950],[5200,1150,5900,2200],[6200,300,7900,850],[8200,450,9300,1800],[6500,2500,7700,3450],[8050,2850,9300,3850],[2850,3900,4300,5200],[4600,3000,5750,4050]];
const water=[[3700,1100,5050,2050],[4200,2850,5150,3650]];const mountains=[[7350,300,9300,1800],[6900,1900,8500,2750],[7350,2750,9300,3900]];
function randQ(){return questions[Math.floor(Math.random()*questions.length)]}function publicPlayer(p){return{id:p.id,name:p.name,pokemon:p.pokemon,x:p.x,y:p.y,level:p.level,xp:p.xp,tokens:p.tokens,wins:p.wins,streak:p.streak,region:regionAt(p.x,p.y).name}}function regionAt(x,y){return regions.find(r=>x>=r.x&&x<r.x+r.w&&y>=r.y&&y<r.y+r.h)||regions[0]}
function save(p){saved[p.name.toLowerCase()]={name:p.name,level:p.level,xp:p.xp,tokens:p.tokens,wins:p.wins,pokemon:p.pokemon,inventory:p.inventory,stats:p.stats,quests:p.quests};persist()}
function sendProgress(s,p){s.emit('progressUpdate',{level:p.level,xp:p.xp,maxXp:p.level*120,tokens:p.tokens,wins:p.wins,streak:p.streak,inventory:p.inventory,stats:p.stats,quests:p.quests})}
function award(s,p,xp,tokens){p.xp+=xp;p.tokens+=tokens;let levels=0;while(p.xp>=p.level*120){p.xp-=p.level*120;p.level++;p.stats.hpMax+=10;p.stats.attack+=3;levels++}save(p);sendProgress(s,p);if(levels)s.emit('levelUp',{level:p.level})}
function broadcast(){io.emit('stateUpdate',Object.fromEntries([...players].map(([id,p])=>[id,publicPlayer(p)])))}
function rank(){io.emit('leaderboardData',[...Object.values(saved)].sort((a,b)=>(b.wins||0)-(a.wins||0)||(b.level||1)-(a.level||1)||(b.tokens||0)-(a.tokens||0)).slice(0,25).map(x=>({name:x.name,level:x.level||1,wins:x.wins||0,tokens:x.tokens||0})))}
function questList(p){return[{id:'first',title:'Primer paso',desc:'Gana 1 combate',done:p.wins>=1},{id:'explorer',title:'Explorador',desc:'Visita 3 pueblos',done:(p.quests.visited||[]).length>=3},{id:'scholar',title:'Académico',desc:'Alcanza nivel 5',done:p.level>=5},{id:'champion',title:'Campeón',desc:'Gana 10 combates',done:p.wins>=10},{id:'streak',title:'Racha maestra',desc:'Consigue una racha de 5',done:(p.quests.bestStreak||0)>=5}]}
function nearestTown(p){return towns.map(t=>({...t,d:Math.hypot(p.x-t.x,p.y-t.y)})).sort((a,b)=>a.d-b.d)[0]}
function startWild(s,p){if(battles.has(s.id))return;const w=wild[Math.floor(Math.random()*wild.length)],lv=clamp(p.level+Math.floor(Math.random()*5)-2,1,100),q=randQ();const enemy={name:w[0],icon:w[1],type:w[2],level:lv,maxHp:w[3]+lv*7,hp:w[3]+lv*7,atk:w[4]+Math.floor(lv/3)};battles.set(s.id,{kind:'wild',enemy,q,started:Date.now()});p.questionAt=Date.now();s.emit('battleStarted',{kind:'wild',enemy,question:{q:q[0],a:q[1],c:q[2],hint:q[3]}})}
function finishWild(s,p,win){battles.delete(s.id);if(win){p.wins++;p.streak++;p.quests.bestStreak=Math.max(p.quests.bestStreak,p.streak);award(s,p,35+p.streak*5,5);s.emit('battleWon',{xp:35+p.streak*5,tokens:5,streak:p.streak})}else{p.streak=0;s.emit('battleLost',{hp:p.stats.hpMax});p.stats.hp=p.stats.hpMax;sendProgress(s,p);save(p)}}
function startPvp(a,b){const ma=mons[a.pokemon]||mons.pikachu,mb=mons[b.pokemon]||mons.pikachu;const room={a:a.id,b:b.id,turn:a.id,qa:randQ(),qb:randQ(),hpA:ma.hp+a.level*6,hpB:mb.hp+b.level*6,maxA:ma.hp+a.level*6,maxB:mb.hp+b.level*6};battles.set(a.id,{kind:'pvp',room});battles.set(b.id,{kind:'pvp',room});a.questionAt=Date.now();b.questionAt=Date.now();io.to(a.id).emit('pvpStarted',{your:true,opponent:{name:b.name,pokemon:b.pokemon,level:b.level,maxHp:room.maxB,hp:room.maxB},yourHp:room.maxA,question:{q:room.qa[0],a:room.qa[1],c:room.qa[2],hint:room.qa[3]}});io.to(b.id).emit('pvpStarted',{your:true,opponent:{name:a.name,pokemon:a.pokemon,level:a.level,maxHp:room.maxA,hp:room.maxA},yourHp:room.maxB,question:{q:room.qb[0],a:room.qb[1],c:room.qb[2],hint:room.qb[3]}})}
function pvpState(id){const b=battles.get(id),r=b&&b.room,p=players.get(id);if(!r||!p)return null;const oppId=r.a===id?r.b:r.a,opp=players.get(oppId);const myHp=id===r.a?r.hpA:r.hpB,oppHp=id===r.a?r.hpB:r.hpA;const q=id===r.a?r.qa:r.qb;return{yourHp:myHp,opponentHp:oppHp,turn:r.turn,opponent:{name:opp.name,pokemon:opp.pokemon,level:opp.level,maxHp:id===r.a?r.maxB:r.maxA},question:{q:q[0],a:q[1],c:q[2],hint:q[3]}}}
app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'public','game-v9.html')));app.get('/health',(req,res)=>res.json({ok:true,version:'9.0 SUPREME',players:players.size,world:`${W}x${H}`,started}));app.use('/assets',express.static(path.join(__dirname,'public')));
io.on('connection',s=>{
 s.on('joinPlayer',(d={})=>{if(players.has(s.id))return;const name=clean(d.name),old=saved[name.toLowerCase()]||{},base=mons[old.pokemon||d.pokemon]||mons.pikachu;const t=towns.find(x=>x.id==='lumen');if(!owner)owner=s.id;const p={id:s.id,name,pokemon:old.pokemon||d.pokemon&&mons[d.pokemon]?d.pokemon:'pikachu',x:Number(d.x)||t.x,y:Number(d.y)||t.y,level:clamp(Number(old.level)||1,1,100),xp:Number(old.xp)||0,tokens:Number(old.tokens)||0,wins:Number(old.wins)||0,streak:0,stats:old.stats||{hp:base.hp, hpMax:base.hp,attack:base.atk},inventory:old.inventory||{snack:3,boost:0,badge:0},quests:old.quests||{visited:['lumen'],bestStreak:0},lastMove:Date.now(),questionAt:0};p.stats.hp=Math.min(p.stats.hp,p.stats.hpMax);players.set(s.id,p);s.emit('serverReady',{id:s.id,owner:s.id===owner,world:{w:W,h:H},towns,regions});sendProgress(s,p);s.emit('questData',questList(p));broadcast();rank();if(started)s.emit('roomStarted')});
 s.on('triggerStart',()=>{if(s.id!==owner)return s.emit('serverError',{message:'Solo el dueño puede iniciar la aventura.'});started=true;io.emit('roomStarted')});
 s.on('playerMove',(d={})=>{const p=players.get(s.id);if(!p)return;const now=Date.now(),dt=Math.min(.3,Math.max(.016,(now-p.lastMove)/1000)),nx=Number(d.x),ny=Number(d.y);if(!Number.isFinite(nx)||!Number.isFinite(ny))return;if(Math.hypot(nx-p.x,ny-p.y)>18*dt+8)return;p.x=clamp(nx,25,W-25);p.y=clamp(ny,25,H-25);p.lastMove=now;const town=nearestTown(p);if(town.d<260&&!p.quests.visited.includes(town.id)){p.quests.visited.push(town.id);save(p);s.emit('questData',questList(p))}broadcast()});
 s.on('wildEncounter',()=>{const p=players.get(s.id);if(!p||!started)return;startWild(s,p)});
 s.on('battleAnswer',(d={})=>{const p=players.get(s.id),b=battles.get(s.id);if(!p||!b||b.kind!=='wild'||Date.now()-p.questionAt<250)return;const ok=Number(d.answer)===b.q[2];const damage=ok?Math.max(1,p.stats.attack+p.level*2):0;if(ok)b.enemy.hp=Math.max(0,b.enemy.hp-damage);else p.streak=0;if(b.enemy.hp<=0)return finishWild(s,p,true);const ed=ok?Math.max(1,b.enemy.atk-4):b.enemy.atk;p.stats.hp=Math.max(0,p.stats.hp-ed);if(p.stats.hp<=0)return finishWild(s,p,false);b.q=randQ();p.questionAt=Date.now();s.emit('battleUpdate',{correct:ok,damage,enemyDamage:ed,enemyHp:b.enemy.hp,playerHp:p.stats.hp,explanation:ok?'Correct!':'Not quite.',question:{q:b.q[0],a:b.q[1],c:b.q[2],hint:b.q[3]}});sendProgress(s,p)});
 s.on('battleRun',()=>{if(battles.has(s.id)){battles.delete(s.id);s.emit('battleEnded',{reason:'run'})}});
 s.on('pvpAnswer',(d={})=>{const p=players.get(s.id),b=battles.get(s.id);if(!p||!b||b.kind!=='pvp'||Date.now()-p.questionAt<250)return;const r=b.room;if(r.turn!==s.id)return;const ok=Number(d.answer)===(s.id===r.a?r.qa[2]:r.qb[2]);const oppId=s.id===r.a?r.b:r.a;const damage=ok?Math.max(5,p.stats.attack+p.level):0;if(s.id===r.a)r.hpB=Math.max(0,r.hpB-damage);else r.hpA=Math.max(0,r.hpA-damage);if((s.id===r.a?r.hpB:r.hpA)<=0){battles.delete(s.id);battles.delete(oppId);p.wins++;award(s,p,60,12);io.to(s.id).emit('pvpWon',{xp:60,tokens:12});io.to(oppId).emit('pvpLost',{name:p.name});rank();return}r.turn=oppId;r.qa=randQ();r.qb=randQ();players.get(oppId).questionAt=Date.now();p.questionAt=Date.now();io.to(s.id).emit('pvpUpdate',pvpState(s.id));io.to(oppId).emit('pvpUpdate',pvpState(oppId))});
 s.on('challengePlayer',id=>{const p=players.get(s.id),t=players.get(String(id));if(!p||!t||t.id===s.id||battles.has(s.id)||battles.has(t.id))return s.emit('serverError',{message:'Ese entrenador no está disponible.'});invites.set(t.id,{from:s.id,expires:Date.now()+15000});io.to(t.id).emit('pvpInvite',{from:s.id,name:p.name,pokemon:p.pokemon,level:p.level})});
 s.on('pvpResponse',d=>{const invite=invites.get(s.id);if(!invite||invite.expires<Date.now())return invites.delete(s.id);invites.delete(s.id);if(!d.accept){io.to(invite.from).emit('pvpResult',{accepted:false,name:players.get(s.id)?.name});return}const a=players.get(invite.from),b=players.get(s.id);if(a&&b)startPvp(a,b)});
 s.on('chatSend',msg=>{const p=players.get(s.id),text=String(msg||'').replace(/[<>]/g,'').trim().slice(0,120);if(p&&text)io.emit('chatMessage',{id:s.id,name:p.name,text,time:Date.now()})});
 s.on('fastTravel',id=>{const p=players.get(s.id),t=towns.find(x=>x.id===id);if(!p||!t)return;if(Math.hypot(p.x-t.x,p.y-t.y)>900)return s.emit('serverError',{message:'Acércate a una estación para usar ZHORXAT FAWND.'});p.x=t.x;p.y=t.y;p.quests.visited.includes(t.id)||p.quests.visited.push(t.id);save(p);s.emit('travelArrived',t);s.emit('questData',questList(p));broadcast()});
 s.on('useItem',id=>{const p=players.get(s.id);if(!p)return;if(id==='snack'&&(p.inventory.snack||0)>0){p.inventory.snack--;p.stats.hp=Math.min(p.stats.hpMax,p.stats.hp+40);save(p);sendProgress(s,p);s.emit('itemUsed',{id})}else if(id==='boost'&&(p.inventory.boost||0)>0){p.inventory.boost--;p.xp+=60;while(p.xp>=p.level*120){p.xp-=p.level*120;p.level++;p.stats.hpMax+=10;p.stats.attack+=3}s.emit('itemUsed',{id});save(p);sendProgress(s,p)}else s.emit('serverError',{message:'No tienes ese objeto.'})});
 s.on('getQuests',()=>{const p=players.get(s.id);if(p)s.emit('questData',questList(p))});s.on('getShop',()=>s.emit('shopData',[{id:'snack',name:'PokéSnack',icon:'🍎',price:8,desc:'Recupera 40 HP'},{id:'boost',name:'EXP Boost',icon:'✨',price:25,desc:'+60 EXP'},{id:'badge',name:'Trainer Badge',icon:'🏅',price:40,desc:'Coleccionable'}]));s.on('buyItem',d=>{const p=players.get(s.id),prices={snack:8,boost:25,badge:40},price=prices[d.id];if(!p||!price||p.tokens<price)return s.emit('serverError',{message:'No tienes suficientes tokens.'});p.tokens-=price;p.inventory[d.id]=(p.inventory[d.id]||0)+1;save(p);sendProgress(s,p);s.emit('itemBought',{id:d.id})});s.on('leaderboard',rank);
 s.on('disconnect',()=>{const p=players.get(s.id);if(p)save(p);players.delete(s.id);battles.delete(s.id);invites.delete(s.id);if(owner===s.id)owner=players.keys().next().value||null;if(!owner)started=false;broadcast();rank()})
});
setInterval(()=>{for(const [id,p] of players){if(Date.now()-p.lastMove>60000){}}},30000);
const PORT=process.env.PORT||3000;server.listen(PORT,()=>console.log(`🎮 PokéWords SUPREME v9 • ${W}x${H}`));