const express=require('express');const http=require('http');const path=require('path');const fs=require('fs');const {Server}=require('socket.io');
const app=express(),server=http.createServer(app),io=new Server(server,{pingInterval:10000,pingTimeout:20000,maxHttpBufferSize:10000}),PORT=Number(process.env.PORT)||10000;
const WORLD={w:9600,h:5400},PUB=path.join(__dirname,'public'),DATA=path.join(__dirname,'data'),FILE=path.join(DATA,'players.json');fs.mkdirSync(DATA,{recursive:true});let saved={};try{saved=JSON.parse(fs.readFileSync(FILE,'utf8'))||{}}catch{}const persist=()=>{try{fs.writeFileSync(FILE,JSON.stringify(saved,null,2))}catch{}};
const regions=[{id:'lumen',name:'Pradera Lumen',x:0,y:0,w:3000,h:1800,color:'#65b96b'},{id:'emerald',name:'Bosque Esmeralda',x:0,y:1800,w:3200,h:3600,color:'#398d56'},{id:'aqua',name:'Lago Azul',x:3000,y:0,w:3000,h:2500,color:'#58aa69'},{id:'nova',name:'Región Nova',x:6000,y:0,w:3600,h:2200,color:'#79bd70'},{id:'red',name:'Montañas Rojas',x:6000,y:2200,w:3600,h:3200,color:'#77736f'},{id:'sky',name:'Costa Sky',x:3200,y:2500,w:2800,h:2900,color:'#5aa76b'}];
const towns=[{id:'lumen',name:'Pueblo Lumen',x:850,y:700,region:'Pradera Lumen'},{id:'aqua',name:'Villa Aqua',x:3900,y:850,region:'Lago Azul'},{id:'nova',name:'Ciudad Nova',x:6900,y:1100,region:'Región Nova'},{id:'verde',name:'Aldea Verde',x:2150,y:3900,region:'Bosque Esmeralda'},{id:'cumbre',name:'Pueblo Cumbre',x:7700,y:3900,region:'Montañas Rojas'},{id:'sky',name:'Puerto Sky',x:5000,y:4550,region:'Costa Sky'}];
const routes=[[850,700,3900,850],[3900,850,6900,1100],[6900,1100,7700,3900],[7700,3900,5000,4550],[5000,4550,2150,3900],[2150,3900,850,700],[3900,850,2150,3900],[5000,4550,6900,1100]];
const grass=[[1150,300,2750,650],[1500,900,2850,1550],[350,2250,1700,3450],[1800,2300,3050,3550],[3000,300,3700,650],[4800,300,5900,950],[5200,1150,5900,2200],[6200,300,7900,850],[8200,450,9300,1800],[6500,2500,7700,3450],[8050,2850,9300,3850],[2850,3900,4300,5200],[4600,3000,5750,4050]];
const water=[[3650,1050,5050,2050],[4200,2850,5150,3650]],mountains=[[7350,300,9300,1800],[6900,1900,8500,2750],[7350,2750,9300,3900]];
const mons={pikachu:{icon:'⚡',type:'Electric',hp:110,atk:22},squirtle:{icon:'💧',type:'Water',hp:125,atk:20},charmander:{icon:'🔥',type:'Fire',hp:105,atk:25},bulbasaur:{icon:'🌿',type:'Grass',hp:120,atk:21},pidgey:{icon:'🪽',type:'Flying',hp:100,atk:23},raichu:{icon:'⚡',type:'Electric',hp:125,atk:27}};
const wild=[['Flameling','🔥','Fire',80,17],['Aquafin','💧','Water',88,15],['Leafling','🌿','Grass',84,16],['Skybit','🪽','Flying',72,19],['Voltimp','⚡','Electric',76,20],['Moonkit','🌙','Dark',90,16],['Pebblit','🪨','Rock',105,13],['Frostel','❄️','Ice',86,18],['Buglet','🐛','Bug',70,15],['Drakid','🐲','Dragon',95,21]];
const questions=[['She _____ to school yesterday.',['go','went','goes','going'],1],['English for “agua”.',['Fire','Water','Earth','Wind'],1],['Past tense of eat?',['eated','eats','ate','eating'],2],['Happy means…',['Triste','Feliz','Rápido','Grande'],1],['They _____ playing football.',['is','am','are','be'],2],['I ___ a student.',['am','is','are','be'],0],['Fast means…',['Lento','Rápido','Pequeño','Frío'],1],['Choose the plural.',['childs','children','childes','child'],1],['Opposite of cold.',['hot','slow','dark','short'],0],['There _____ two books.',['is','are','am','be'],1],['My sister _____ a bike every day.',['ride','rides','riding','rode'],1],['Translate: “I like music.”',['Me gusta la música.','Odio la música.','Toco fútbol.','Escucho agua.'],0]];
const players=new Map(),battles=new Map(),invites=new Map();let owner=null;
const clean=s=>String(s||'Trainer').replace(/[^a-zA-Z0-9 _-]/g,'').trim().slice(0,18)||'Trainer',clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),q=()=>questions[Math.floor(Math.random()*questions.length)],inGrass=(x,y)=>grass.some(g=>x>=g[0]&&x<=g[2]&&y>=g[1]&&y<=g[3]),regionAt=(x,y)=>regions.find(r=>x>=r.x&&x<r.x+r.w&&y>=r.y&&y<r.y+r.h)||regions[0];
function publicPlayer(p){return{id:p.id,name:p.name,pokemon:p.pokemon,x:p.x,y:p.y,level:p.level,xp:p.xp,tokens:p.tokens,wins:p.wins,streak:p.streak,region:regionAt(p.x,p.y).name}}function broadcast(){io.emit('stateUpdate',Object.fromEntries([...players].map(([id,p])=>[id,publicPlayer(p)])))}function progress(s,p){s.emit('progressUpdate',{level:p.level,xp:p.xp,maxXp:p.level*120,tokens:p.tokens,wins:p.wins,streak:p.streak,inventory:p.inventory,stats:p.stats})}function save(p){saved[p.name.toLowerCase()]={name:p.name,level:p.level,xp:p.xp,tokens:p.tokens,wins:p.wins,pokemon:p.pokemon,inventory:p.inventory,stats:p.stats,quests:p.quests};persist()}function award(s,p,xp,tokens){p.xp+=xp;p.tokens+=tokens;while(p.xp>=p.level*120){p.xp-=p.level*120;p.level++;p.stats.hpMax+=10;p.stats.attack+=3;s.emit('levelUp',{level:p.level})}save(p);progress(s,p)}
function startWild(s,p){if(battles.has(s.id))return;const w=wild[Math.floor(Math.random()*wild.length)],lv=clamp(p.level+Math.floor(Math.random()*5)-2,1,100),hp=w[3]+lv*7,z=q(),enemy={name:w[0],icon:w[1],type:w[2],level:lv,maxHp:hp,hp,atk:w[4]+Math.floor(lv/3)};battles.set(s.id,{kind:'wild',enemy,q:z});p.questionAt=Date.now();s.emit('battleStarted',{enemy,question:{q:z[0],a:z[1],c:z[2],hint:''}})}
app.disable('x-powered-by');app.get('/health',(req,res)=>res.json({ok:true,version:'STABLE-1',world:WORLD,players:players.size}));app.get('/',(req,res)=>res.sendFile(path.join(PUB,'game-v9.html')));app.use(express.static(PUB));
io.on('connection',s=>{s.emit('serverInfo',{id:s.id,world:WORLD,towns,regions,routes,grass,water,mountains});s.on('joinPlayer',(d={})=>{const requested=clean(d.name),chosen=mons[d.pokemon]?d.pokemon:'pikachu';if(players.has(s.id)){const p=players.get(s.id);p.name=requested;p.pokemon=chosen;save(p);progress(s,p);broadcast();return}const old=saved[requested.toLowerCase()]||{},mon=old.pokemon||chosen,base=mons[mon]||mons.pikachu,t=towns[0];if(!owner)owner=s.id;const p={id:s.id,name:requested,pokemon:mon,x:t.x,y:t.y,level:clamp(Number(old.level)||1,1,100),xp:Number(old.xp)||0,tokens:Number(old.tokens)||0,wins:Number(old.wins)||0,streak:0,stats:old.stats||{hp:base.hp,hpMax:base.hp,attack:base.atk},inventory:old.inventory||{snack:3,boost:0,badge:0},quests:old.quests||{visited:['lumen'],bestStreak:0},lastMove:Date.now(),questionAt:0};p.stats.hp=Math.min(p.stats.hp,p.stats.hpMax);players.set(s.id,p);s.emit('serverReady',{id:s.id,owner:s.id===owner,world:WORLD,towns,regions,routes,grass,water,mountains});progress(s,p);broadcast();io.emit('chatMessage',{name:'SYSTEM',text:p.name+' se unió a la aventura.'})});
s.on('playerMove',(d={})=>{const p=players.get(s.id);if(!p)return;const nx=Number(d.x),ny=Number(d.y);if(!Number.isFinite(nx)||!Number.isFinite(ny))return;const now=Date.now(),dt=Math.min(.35,Math.max(.016,(now-p.lastMove)/1000));if(Math.hypot(nx-p.x,ny-p.y)>220*dt+25)return;p.x=clamp(nx,24,WORLD.w-24);p.y=clamp(ny,24,WORLD.h-24);p.lastMove=now;broadcast()});
s.on('wildEncounter',()=>{const p=players.get(s.id);if(p&&inGrass(p.x,p.y))startWild(s,p)});
s.on('battleAnswer',(d={})=>{const p=players.get(s.id),b=battles.get(s.id);if(!p||!b||b.kind!=='wild'||Date.now()-p.questionAt<200)return;const ok=Number(d.answer)===b.q[2];if(ok)b.enemy.hp=Math.max(0,b.enemy.hp+p.stats.attack+p.level*2*-1);p.stats.hp=Math.max(0,p.stats.hp-(ok?Math.max(1,b.enemy.atk-4):b.enemy.atk));if(b.enemy.hp<=0){battles.delete(s.id);p.wins++;p.streak++;award(s,p,35+p.streak*5,5);return s.emit('battleWon',{xp:35+p.streak*5,tokens:5,streak:p.streak})}if(p.stats.hp<=0){battles.delete(s.id);p.streak=0;p.stats.hp=p.stats.hpMax;save(p);progress(s,p);return s.emit('battleLost',{hp:p.stats.hpMax})}b.q=q();p.questionAt=Date.now();s.emit('battleUpdate',{correct:ok,damage:ok?p.stats.attack+p.level*2:0,enemyDamage:ok?Math.max(1,b.enemy.atk-4):b.enemy.atk,enemyHp:b.enemy.hp,playerHp:p.stats.hp,question:{q:b.q[0],a:b.q[1],c:b.q[2],hint:''}})});
s.on('battleRun',()=>{if(battles.has(s.id)){battles.delete(s.id);s.emit('battleEnded')}});s.on('chatSend',text=>{const p=players.get(s.id);if(p){const m=String(text||'').replace(/[<>]/g,'').trim().slice(0,120);if(m)io.emit('chatMessage',{name:p.name,text:m})}});
s.on('fastTravel',id=>{const p=players.get(s.id),t=towns.find(x=>x.id===id);if(!p||!t)return;p.x=t.x;p.y=t.y;p.quests.visited.includes(t.id)||p.quests.visited.push(t.id);save(p);s.emit('travelArrived',t);broadcast()});s.on('getQuests',()=>{const p=players.get(s.id);if(p)s.emit('questData',[{title:'Primer paso',desc:'Gana 1 combate',done:p.wins>=1},{title:'Explorador',desc:'Visita 3 pueblos',done:p.quests.visited.length>=3},{title:'Académico',desc:'Alcanza nivel 5',done:p.level>=5}])});s.on('getShop',()=>s.emit('shopData',[{id:'snack',name:'PokéSnack',icon:'🍎',price:10,desc:'Recupera HP.'},{id:'boost',name:'EXP Boost',icon:'✨',price:30,desc:'Objeto de experiencia.'}]));s.on('buyItem',({id}={})=>{const p=players.get(s.id),prices={snack:10,boost:30};if(!p||!prices[id]||p.tokens<prices[id])return s.emit('serverError',{message:'No tienes suficientes Tokens.'});p.tokens-=prices[id];p.inventory[id]=(p.inventory[id]||0)+1;save(p);progress(s,p);s.emit('itemBought',{id})});s.on('leaderboard',()=>s.emit('leaderboardData',Object.values(saved).sort((a,b)=>(b.wins||0)-(a.wins||0)).slice(0,25).map(x=>({name:x.name,level:x.level||1,wins:x.wins||0,tokens:x.tokens||0}))));
s.on('challenge',target=>{const a=players.get(s.id),b=players.get(target);if(a&&b){invites.set(b.id,{from:a.id,expires:Date.now()+15000});io.to(b.id).emit('challengeInvite',{from:a.id,name:a.name,pokemon:a.pokemon,level:a.level})}});s.on('challengeResponse',({accept}={})=>{const i=invites.get(s.id);if(!i||i.expires<Date.now()){invites.delete(s.id);return}const a=players.get(i.from),b=players.get(s.id);invites.delete(s.id);if(!accept||!a||!b)return io.to(i.from).emit('challengeResult',{accepted:false});io.to(i.from).emit('challengeResult',{accepted:true});io.to(s.id).emit('challengeResult',{accepted:true})});s.on('disconnect',()=>{const p=players.get(s.id);if(p)io.emit('chatMessage',{name:'SYSTEM',text:p.name+' salió.'});players.delete(s.id);battles.delete(s.id);invites.delete(s.id);if(owner===s.id)owner=players.keys().next().value||null;broadcast()})});
server.listen(PORT,'0.0.0.0',()=>console.log(`PokéWords STABLE listening on ${PORT}`));
